# Generated by Django 4.2.7 on 2025-11-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('oyente', 'Oyente'), ('sordo', 'Sordo'), ('mudo', 'Mudo'), ('sordomudo', 'Sordomudo')], max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'), models.Index(fields=['tipo_usuario'], name='usuarios_tipo_us_3a6d09_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('tamaño_fuente', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=20)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('alto_contraste', 'Alto Contraste')], default='claro', max_length=30)),
                ('velocidad_animaciones', models.CharField(choices=[('lenta', 'Lenta'), ('normal', 'Normal'), ('rapida', 'Rápida')], default='normal', max_length=20)),
                ('notificaciones_habilitadas', models.BooleanField(default=True)),
                ('sonido_habilitado', models.BooleanField(default=True)),
                ('vibracion_habilitada', models.BooleanField(default=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
                'db_table': 'configuraciones_usuario',
            },
        ),
    ]
