# Generated by Django 4.2.7 on 2025-11-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_contrasena_usuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contraseña',
        ),
    ]
