# Generated by Django 4.2.7 on 2025-11-23 21:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSeña',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Seña',
                'verbose_name_plural': 'Categorías de Señas',
                'db_table': 'categorias_seÃ±as',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DiccionarioSeña',
            fields=[
                ('id_seña', models.AutoField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_video', models.URLField(blank=True, null=True)),
                ('url_imagen', models.URLField(blank=True, null=True)),
                ('url_animacion', models.URLField(blank=True, null=True)),
                ('duracion_video_segundos', models.IntegerField(blank=True, null=True)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=20)),
                ('popularidad', models.IntegerField(default=0)),
                ('veces_practicada', models.IntegerField(default=0)),
                ('etiquetas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Etiquetas para búsqueda', size=None)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='señas', to='diccionario.categoriaseña')),
            ],
            options={
                'verbose_name': 'Seña',
                'verbose_name_plural': 'Señas',
                'db_table': 'diccionario_seÃ±as',
                'ordering': ['palabra'],
                'indexes': [models.Index(fields=['palabra'], name='diccionario_palabra_e37ddb_idx'), models.Index(fields=['id_categoria'], name='diccionario_id_cate_13606b_idx'), models.Index(fields=['dificultad'], name='diccionario_dificul_7f2502_idx')],
            },
        ),
    ]
